# Python functions in Physics class (physics_class.py)
# Practice using Python functions by calculating some physical properties.

# Define function to convert Fahrenheit into Celsius
def f_to_c(fahrenheit_temp):
  return (fahrenheit_temp - 32) * (5 / 9)

fahrenheit100_to_celsius = f_to_c(100)
print(f'\n100°F convert to {fahrenheit100_to_celsius:.2f}°C.\n')

# Define function to convert Celsius into Fahrenheit
def c_to_f(celsius_temp):
  return celsius_temp * (9 / 5) + 32

celsius0_to_fahrenheit = c_to_f(0)
print(f'0°C convert to {celsius0_to_fahrenheit}°F.\n')

# Define function to calculate force generated by a train
def calc_force(mass, acceleration):
  return mass * acceleration

train_mass = 22680
train_acceleration = 10

train_force = calc_force(train_mass, train_acceleration)
print(f'The GE train supplies {train_force} N.\n')

# Define function to calculate work generated by a train
def calc_work(distance):
  return train_force * distance

train_distance = 100

train_work = calc_work(train_distance)
print(f'The GE train does {train_work} J of work over {train_distance} meters.\n')

# Define function to calculate the energy generated by a bomb
def calc_energy(mass):
  from scipy.constants import c
  return mass * (c * c)

bomb_mass = 1

bomb_energy = calc_energy(bomb_mass)
print(f'A 1kg bomb supplies {bomb_energy} J.\n')


